apiVersion: v1
kind: Secret
metadata:
  name: aws-rds-postgres-secret
type: Opaque
data:
  # base64 - o Kind Secret realiza o conversao automatica.
  AWS_RDS_POSTGRES_USER: cG9zdGdyZXM=
  AWS_RDS_POSTGRES_PASSWORD: Z2VyYWRvckAxMjM=