name: Build CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  PROJECT_NAME: 'gerador-uuid-core'
  RDS_DB_NAME: 'gerador-uuid-rds'
  JAVA_VERSION: '17.0.13'
  DISTRIBUTION: 'zulu'
  AWS_REGION: 'us-east-1'

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.DISTRIBUTION}}
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.DISTRIBUTION}}

      - name: Run Unit Tests
        run: mvn -B test

  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.DISTRIBUTION}}

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=CaioMC_gerador-uuid-core

  push-to-aws-ecr:
    name: Publish Docker Image to Amazon ECR
    runs-on: ubuntu-latest
    needs: sonar

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: app

      # ðŸ”¹ Configurar AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug github.run_number
        run: |
          echo "Run number: ${{ github.run_number }}"

      - name: Build and Push Docker image to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.run_id }}

  aws-deploy-manifest:
    name: Deploy Manifest AWS EKS
    runs-on: ubuntu-latest
    needs: push-to-aws-ecr
    steps:
      # ðŸ”¹ Configurar AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Checkout source
        uses: actions/checkout@v4

      # ðŸ”¹ Instalar kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      # ðŸ”¹ Atualizar kubeconfig para o cluster EKS
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{env.AWS_REGION}} --name ${{ env.PROJECT_NAME }}

      - name: Atualizar e aplicar ConfigMap com endpoint do RDS
        run: |
          RDS_ENDPOINT=$(aws rds describe-db-instances \
            --db-instance-identifier ${{ env.RDS_DB_NAME }} \
            --query "DBInstances[0].Endpoint.Address" \
            --output text)
          sed -i "s|{{RDS_ENDPOINT}}|$RDS_ENDPOINT|g" ./devops/k8s/prod/database/env/aws-rds-postgres-configmap.yaml

      # ðŸ”¹ Deploy no Kubernetes
      - name: Deploy to EKS
        run: |
          chmod +x ./devops/scripts/deploy-k8s-prod.sh
          ./devops/scripts/deploy-k8s-prod.sh